version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./Oil-Spill-Detection-in-Marine-Environments-Using-AIS-and-Satellite-Data:/data
    environment:
      - DATA_DIR=/data
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_CARTO_API_KEY=cb1_2krl_1_8d5202e6f7970176b1a30773
    depends_on:
      - backend
    restart: unless-stopped
